[package]
name = "hive"
version = "0.1.403"
authors = ["Enoch Carter <mrenoch@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
license-file = "LICENSE.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
#tokio = {version = "0.2.21", features = ["macros", "rt-core", "sync", "tcp"]}
#https://docs.rs/config/0.10.1/config/
config = "0.10.1"
toml = "0.5"
log = "0.4.11"

#libusb = "0.3"
#usbd-serial = "0.1"
#usb-device = "0.2.5"

#async-std = { git = 'https://github.com/stjepang/async-std', branch = 'new-scheduler' }
async-std = "1.6.2"

[lib]
name = "hive"
# this is needed to build for iOS and Android.
crate-type = ["staticlib", "cdylib", "lib"]

# this dependency is only needed for Android.
[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.13.1", default-features = false }