[package]
name = "hive"
version = "0.1.403"
authors = ["Enoch Carter <mrenoch@gmail.com>"]
edition = "2018"
license-file = "LICENSE.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["bluetooth"]
bluetooth = ["bluster", "blurz", "uuid", "tokio", "lazy_static", "regex"]

[dependencies]
futures = "0.3"
#https://docs.rs/config/0.10.1/config/
config = "0.10.1"
toml = "0.5"
log = "0.4.11"
async-std = "1.8"
simple-signal = "1.1.1"
bytes = "0.6"
local_ipaddress = "0.1"
#crossbeam = "0.8.0"
bluster =     {git="https://github.com/dfrankland/bluster", branch="master", optional=true}
uuid =        {version="0.8.1", optional=true}
tokio =       {version="0.2", optional=true}
lazy_static = {version="1.4.0", optional=true}
# regix version limited by serd_hjson / config
regex =       {version="1.0", optional=true}


[target.'cfg(target_os = "linux")'.dependencies]
blurz = {version="0.4.0", optional=true}
#blurz = {path="../blurz", optional=true}

#libusb = "0.3"
#usbd-serial = "0.1"
#usb-device = "0.2.5"

#async-std = { git = 'https://github.com/stjepang/async-std', branch = 'new-scheduler' }


[lib]
name = "hive"
# this is needed to build for iOS and Android.
crate-type = ["staticlib", "cdylib", "lib"]

# this dependency is only needed for Android.
[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.13.1", default-features = false }