[package]
name = "hive"
version = "0.1.403"
authors = ["Enoch Carter <mrenoch@gmail.com>"]
edition = "2018"
license-file = "LICENSE.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["websock"]
#default = []
bluetooth = ["bluster", "blurz", "uuid", "tokio", "lazy_static", "regex"]
websock = ["websocket-codec", "base64", "sha-1", "tokio-util"]

[dependencies]
futures = "0.3"
#futures-lite = "1.11.3", can't quite use the lite lib.
#https://docs.rs/config/0.10.1/config/
config = "0.10.1"
toml = "0.5"
log = "0.4.11"
#async-std = "1.8"
async-std = "1.9.0"
# lesten for kill signal to close processes nicely
simple-signal = "1.1.1"

# bytes version limited to reduce duplication wit bluetooth
#bytes = "0.6"
bytes = "1.0.1"
local_ipaddress = "0.1"
bluster =     {git="https://github.com/dfrankland/bluster", branch="master", optional=true}
uuid =        {version="0.8.1", optional=true}
tokio =       {version="0.2", optional=true}
lazy_static = {version="1.4.0", optional=true}
# regix version limited by serd_hjson / config
regex =       {version="1.0", optional=true}

# websocket optionals
#websocket =   "0.26.2"
# git@github.com:1tgr/rust-websocket-lite.git
websocket-codec =    { verstion = "0.5.0", optional = true }
#websocket-codec =    { path = "../websocket-codec", optional = true }
base64 =             { version = "0.13.0", optional = true }
sha-1 =              { version = "0.8", optional = true }
tokio-util =         { version = "0.6.2", optional = true }


[target.'cfg(target_os = "linux")'.dependencies]
blurz = { version = "0.4.0", optional = true }
# bluz is depebdent on dbus which requires libdbus-1-dev

#libusb = "0.3"
#usbd-serial = "0.1"
#usb-device = "0.2.5"


[lib]
name = "hive"
# this is needed to build for iOS and Android.
crate-type = ["staticlib", "cdylib", "lib"]

# this dependency is only needed for Android.
[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.13.1", default-features = false }