import { Slider } from "std-widgets.slint";

component PropertyButton inherits Rectangle {
    callback clicked;
    in property <string> name;
    in property <string> value;

    HorizontalLayout {
       min-width: 200px;
       preferred-width: 400px;
        alignment: start;
//        padding-left:10px;
        Text {
                text: name+": ";
            }
        Text {
            text: value;
        }
    }

    TouchArea {
        clicked => {
            // Delegate to the user of this element
            root.clicked();
        }
    }
}

struct HProperty {
    name: string,
    value: string,
}

export component MainWindow inherits Window {

    min-width: 200px;
    preferred-width: 500px;

    in-out property <[HProperty]> properties: [
        {name:"1", value:"one"},
        {name:"2", value:"two"}
    ];


    callback check_if_pair_solved();
    in property <bool> disable_tiles;

    VerticalLayout {
    padding:20px;
    width:parent.width;
    alignment:center;
        for prop[i] in properties: PropertyButton {
            name: prop.name;
            value: prop.value;
        }

        Slider {

            width: 300px;

        }
    }

}
