import { Slider } from "std-widgets.slint";


export component MainWindow inherits Window {

    min-width: 200px;
    preferred-width: 500px;

    property <float> m1;
    property <float> m2;

    VerticalLayout {
            Slider {
                value: 0;
                width: 300px;
                changed => {
//                    m2 = self.value;
                    s2.value = self.value;
                }
            }
            s2:=Slider {
                value: m2;
                width: 300px;
            }

    }
}
